### ISSUE TITLE
Combination of facets & ggside

### ISSUE THREAD

**Issue by LoreVE** [jtlandis/ggside#3]
Hi

I really like this addition to ggplot2! 

But I seem to run into a problem when I want to add a facet_wrap/facet_grid to the plot with side plots (or if I have facet_wrap/facet_grid plot to which I want to add side plots). So I would like to have a facetted plot with side plots for each facet. 
This is the code I tried
`ScoreLengthPoint <- ggplot(VSTEST0, aes(log10(Length), Score, fill = Final_Classification, colour = Final_Classification)) +
geom_point(alpha = 0.2) +  
facet_wrap(~ Split) +   
geom_xsidedensity(aes(y = stat(density)))`

If I remove either the facet_wrap or geom_xsidedensity it works as expected, but not when I combine both. Then I get the following error:

`Error in `[.data.frame`(x, by) : undefined columns selected`

I would appreciate your help! 

Cheers

**Comment by LoreVE** [comment]
For some reason it works now, not sure what I changed. Sorry to disturb you!

**Comment by modche** [comment]
I run into the same problem. At the moment I cannot make a reproducible example as the data set is really large etc.
Perhaps someone can help?

```
Error in `[.data.frame`(x, by) : undefined columns selected
```

Hier a snapshot of the data:

```# A tibble: 10 × 11
   model  loc                     year precip    et q_dir  q_int  perc q_obs q_bas q_short
   <chr>  <chr>                  <dbl>  <dbl> <dbl> <dbl>  <dbl> <dbl> <dbl> <dbl>   <dbl>
 1 roger  177_Rot                 2015  1071.  631. 29.4   189.   335.  513. 317.     350.
 2 larsim 2444_Fichtenberger Rot  2017    NA    NA  67.6   172.   124.   NA   NA       NA 
 3 train  1111_Wurzacher Ach      2016  1304.  594. 11.4    NA    707.  547. 249.     312.
 4 larsim 205_Brehmbach           2000    NA    NA   2.19   67.4  116.  212.  91.7    187.
 5 train  205_Brehmbach           2011   670.  456. 10.8    NA    288.  259.  97.2    200.
 6 train  422_Erms                2019  1205.  568. 36.8    NA    600.  606.  NA       NA 
 7 roger  396_Acher               2002  2329.  588. 28.3  1112.   683. 1517. 484.     723.
 8 gwnbw  2365_Rotbach            2002  1737.  725. 25.6    NA   1020. 1178. 243.     475.
 9 larsim 3318_Kleine Wiese       2009    NA    NA  51.8   430.   259.  744. 263.     460.
10 roger  380_Neumagen            2018  1311.  475. 19.8   599.   352.  568. 109.     232.
```

Here the ggplot call:
```
df2 %>% pivot_longer(cols = c(precip:perc), names_to = 'var', values_to = 'mm') %>% 
		mutate(var = factor(var, levels = c('precip', 'et', 'q_dir', 'q_int', 'perc'))) %>% 
		ggplot(aes(x = mm, y = q_obs, colour = model)) +
			geom_abline() +
			geom_point(aes(y = q_obs), colour = "cyan4", size = .3) +
			geom_point(aes(y = q_bas), colour = "darkorange", size = .3) +
			facet_grid(model ~ var) +
			theme_bw(15) +
			theme(axis.text.x = element_text(angle=90, vjust=0.5, hjust=1)) +
			scale_y_continuous(limits = c(0,2200), expand = c(0,0)) +
			geom_xsideboxplot(aes(y=model), orientation = "y") +
			scale_xsidey_discrete() +
			ggside(collapse = 'x') 
```

Without ggside code it look like this. I want to compare the models (in the rows) on top of the panel columns.

<img width="522" alt="image" src="https://user-images.githubusercontent.com/13642619/155553058-9660e227-eafb-493a-bb3f-f4a3466e57cd.png">


Btw, really nice package! Thanks a lot!
Michael

**Comment by modche** [comment]
🙄 Ok, I found the problem. The line geom_abline() is causing the error, removing this line, everything is working. An other example of reducing ggplot calls to a minimum to identify the problem.

**Comment by modche** [comment]
Hi. When I put ```geom_abline(aes(slope = 1, intercept = 0))```at the end of the code block and `slope` and `intercept` are defined, then it worked again.

**Comment by jtlandis** [comment]
Hello everyone, 

I have at least located the issue in my code, which is centered around an internal `map_data_ggside()` function. The reason it fails on the `geom_abline` (and I suspect `geom_hline()` and `geom_vline()`) is because it currently expects there to be facet columns generated which isnt the case for these functions.

> These geoms act slightly differently from other geoms. You can supply the parameters in two ways: either as arguments to the layer function, or via aesthetics. If you use arguments, e.g. geom_abline(intercept = 0, slope = 1), **then behind the scenes the geom makes a new data frame containing just the data you've supplied.** That means that the lines will be the same in all facets; if you want them to vary across facets, construct the data frame yourself and use aesthetics.

I will see what I can do to resolve this bug.

**Comment by jtlandis** [comment]
Issue is now resolved on `dev` branch. Once I make progress on all current issues I'll work towards releasing a new patch for ggside

**Comment by MarekGierlinski** [comment]
Hi, great package! The issue with abline/hline/vline still persists. Any chances you could release a patch for this soon?

**Comment by jtlandis** [comment]
Hello, those issues have been fixed on the `dev` branch. I have decided to knock out some lingering issues/feature requests and hopefully I can merge and submit to CRAN tonight.

**Comment by jtlandis** [comment]
The new release of `ggside` is available on CRAN officially.
